Add Ubuntu (22.04 LTS) build dependencies requirements
ljoonal/NeosPeeps pull request #4
Opened 2022-06-14 14:32 UTC by brodokk

Hello, this is not much but could help the next person trying to build on Ubuntu 22.04 LTS.

2022-06-14 14:53 UTC, ljoonal commented on README.md
>  Start off by cloning the project with git.
The build instructions would now fall under the header of the Ubuntu

2022-06-14 14:54 UTC, ljoonal requested changes
It'd probably be saner to make a new header between Developement and building for requirements and move them there.

2022-06-15 10:10 UTC, brodokk commented
> It'd probably be saner to make a new header between Developement and building for requirements and move them there.

Hum... yeah you right, I have another idea. Le me try with another commit directly

2022-06-15 10:19 UTC, brodokk commented
Ok I finally do like you said, my other idea was to put the requirements under the build section but they should be before otherwise it feel not organized

2022-06-15 14:25 UTC, l-2-j approved these changes

2022-06-15 14:27 UTC, merged